version: 1
disable_existing_loggers: no
formatters:
  console_formatter_consumer:
    (): consumer.logger.ConsoleFormatter
  console_formatter_backend:
    (): src.logger.ConsoleFormatter
  file_formatter:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console_handler_backend:
    class: logging.StreamHandler
    formatter: console_formatter_backend
  console_handler_consumer:
    class: logging.StreamHandler
    formatter: console_formatter_consumer
  file_handler_backend:
    class: logging.FileHandler
    filename: 'backend.log'
    level: WARNING
    formatter: file_formatter
  file_handler_consumer:
    class: logging.FileHandler
    filename: 'consumer.log'
    level: WARNING
    formatter: file_formatter

root:
  level: INFO
  handlers: [console_handler_backend, file_handler_backend]

loggers:
  'backend_logger':
    level: INFO
    propagate: no
    handlers: [console_handler_backend, file_handler_backend]
  'consumer_logger':
    level: INFO
    propagate: no
    handlers: [console_handler_consumer, file_handler_consumer]
  'uvicorn':
    level: INFO
    propagate: yes
